### ISSUE TITLE
cant require file

### ISSUE THREAD

**Issue by nousacademy** [leonid-shevtsov/headless#77] opened 2016-01-20 17:11 UTC
I get the error of 
<code> /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- headless (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from test.rb:10:in `<main>'</code>

When I require it like so <code>require 'headless'</code>

When i do <code>gem list</code> it shows up. I don't know what Im doing wrong. Help would be greatly appreciated!

**Comment by erkki** [comment] 2016-02-08 11:03
duplicate of https://github.com/leonid-shevtsov/headless/issues/74

**Comment by leonid-shevtsov** [comment] 2016-08-17 18:41
Closing as 2.2.2 should have this fixed for good.

**Closed by leonid-shevtsov** 2016-08-17 18:41 UTC
